### ISSUE TITLE
/usr/bin/env: “tclsh”: file not found

### ISSUE THREAD

**Issue by rafaelhipercg** [flathub/com.github.git_cola.git-cola#1]
Pressing pull or push give me this error:

```
/usr/bin/env: “tclsh”: file not found
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by davvid** [comment]
I suspect it's the ssh-askpass script. It uses tcl/tk so that might have to be provided in the flatpak as well so that it can launch the dialog prompt.

Does git prompt for your password every time you pull? Using a git credentials manager can avoid this issue as well.

```
git config --globla credential.helper store

# this should prompt for your credentials
git pull

# subsequent calls should not prompt
git pull
```

If you run that then it'll let git remember your credentials and then you won't run into this dialog inside cola either.

For the flatpak authors -- how do we add tcltk to the flatpak environment?
